// Synth XR Presets

const createPreset = (name, category, settings) => ({
    name,
    category,
    settings
});

const builtInPresets = [
    createPreset("Default", "pad", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "900",
        filterRes: "5",
        filterType: false,
        reverbMix: "0.6",
        reverbDecay: "3.5",
        delayTime: "0.33",
        delayFeedback: "0.55",
        tempo: "96",
        attack: "0.02",
        decay: "0.18",
        sustain: "0.35",
        release: "1.4",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0.1",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "1",
        lfoAmount: "50",
        lfoDestination: "off",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2",
        eqMid: "0",
        eqHigh: "1",
        eqMidFreq: "1000",
        eqQ: "1",
        compressor: "0.3",
        sequencer: [
            {"note": "E3", "active": true},
            {"note": "B3", "active": true},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "B3", "active": true},
            {"note": "C4", "active": false},
            {"note": "G3", "active": true},
            {"note": "D4", "active": true},
            {"note": "B3", "active": true},
            {"note": "D4", "active": false},
            {"note": "F#3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E3", "active": true},
            {"note": "B3", "active": true}
        ],
    }),

    // ==== PAD PRESETS ====
    createPreset("Ethereal Waves", "pad", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "1200",
        filterRes: "2",
        filterType: false,
        reverbMix: "0.85",
        reverbDecay: "8.0",
        delayTime: "0.5",
        delayFeedback: "0.4",
        tempo: "80",
        attack: "1.5",
        decay: "2.0",
        sustain: "0.7",
        release: "4.0",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth
        oscillatorLevel: "0.7",
        chorusMix: "0.3",
        distortionMix: "0",
        flangerMix: "0.15",
        phaserMix: "0.1",
        lfoRate: "0.08",
        lfoAmount: "45",
        lfoDestination: "eqMidFreq",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "3",
        eqMid: "-1",
        eqHigh: "2",
        eqMidFreq: "800",
        eqQ: "0.8",
        compressor: "0.3",
        sequencer: [
            {"note": "A3", "active": true},
            {"note": "C4", "active": false},
            {"note": "E4", "active": true},
            {"note": "A4", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "F3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C4", "active": true},
            {"note": "F4", "active": false},
            {"note": "E3", "active": true},
            {"note": "G3", "active": false},
            {"note": "B3", "active": true},
            {"note": "E4", "active": false}
        ],
    }),
    
    createPreset("Cosmic Atmosphere", "pad", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "800",
        filterRes: "4",
        filterType: false,
        reverbMix: "0.9",
        reverbDecay: "7.5",
        delayTime: "0.75",
        delayFeedback: "0.6",
        tempo: "72",
        attack: "2.0",
        decay: "1.5",
        sustain: "0.8",
        release: "5.0",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.75",
        chorusMix: "0.4",
        distortionMix: "0.05",
        flangerMix: "0.2",
        phaserMix: "0.15",
        lfoRate: "0.04",
        lfoAmount: "70",
        lfoDestination: "eqMidFreq",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "4",
        eqMid: "-2",
        eqHigh: "3",
        eqMidFreq: "700",
        eqQ: "0.7",
        compressor: "0.3",
        sequencer: [
            {"note": "C3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "C5", "active": false},
            {"note": "G4", "active": true},
            {"note": "E4", "active": false},
            {"note": "C4", "active": true},
            {"note": "G3", "active": false},
            {"note": "E3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "C5", "active": false}
        ],
    }),
    
    createPreset("Floating Dreams", "pad", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "600",
        filterRes: "6",
        filterType: true,
        reverbMix: "0.8",
        reverbDecay: "6.0",
        delayTime: "0.4",
        delayFeedback: "0.5",
        tempo: "88",
        attack: "1.2",
        decay: "1.8",
        sustain: "0.6",
        release: "3.5",
        oscillatorOctave: "0",
        oscillatorSemi: "4", // Major third
        oscillatorLevel: "0.65",
        chorusMix: "0.35",
        distortionMix: "0.02",
        flangerMix: "0.1",
        phaserMix: "0.2",
        lfoRate: "0.05",
        lfoAmount: "60",
        lfoDestination: "filterCutoff",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2.5",
        eqMid: "0",
        eqHigh: "1.5",
        eqMidFreq: "900",
        eqQ: "0.9",
        compressor: "0.3",
        sequencer: [
            {"note": "F3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C4", "active": true},
            {"note": "F4", "active": false},
            {"note": "D#3", "active": true}, // Changed from Eb3
            {"note": "G3", "active": false},
            {"note": "A#3", "active": true}, // Changed from Bb3
            {"note": "D#4", "active": false}, // Changed from Eb4
            {"note": "A#2", "active": true}, // Changed from Bb2
            {"note": "D3", "active": false},
            {"note": "F3", "active": true},
            {"note": "A#3", "active": false}, // Changed from Bb3
            {"note": "C3", "active": true},
            {"note": "E3", "active": false},
            {"note": "G3", "active": true},
            {"note": "C4", "active": false}
        ],
    }),

    // ==== KEYS PRESETS ====
    createPreset("Crystal Piano", "keys", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "3500",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.45",
        reverbDecay: "2.5",
        delayTime: "0.2",
        delayFeedback: "0.15",
        tempo: "110",
        attack: "0.01",
        decay: "1.2",
        sustain: "0.4",
        release: "0.8",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.9",
        chorusMix: "0.1",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "3.5",
        lfoAmount: "20",
        lfoDestination: "oscillatorLevel",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "0.5",
        eqHigh: "2.5",
        eqMidFreq: "1200",
        eqQ: "1.2",
        compressor: "0.3",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "C5", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "C4", "active": false},
            {"note": "E4", "active": true},
            {"note": "A4", "active": false},
            {"note": "F3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C4", "active": true},
            {"note": "F4", "active": false}
        ]
    }),
    
    createPreset("Vintage Electric", "keys", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "2000",
        filterRes: "3",
        filterType: false,
        reverbMix: "0.3",
        reverbDecay: "1.5",
        delayTime: "0.15",
        delayFeedback: "0.2",
        tempo: "120",
        attack: "0.03",
        decay: "0.8",
        sustain: "0.5",
        release: "0.4",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0.2",
        distortionMix: "0.15",
        flangerMix: "0",
        phaserMix: "0.2",
        lfoRate: "0.05",
        lfoAmount: "50",
        lfoDestination: "attack",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1.5",
        eqMid: "-1",
        eqHigh: "3",
        eqMidFreq: "1000",
        eqQ: "1",
        compressor: "0.3",
        sequencer: [
            {"note": "E3", "active": true},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "E3", "active": true},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true}
        ]
    }),
    
    createPreset("Warm Rhodes", "keys", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "1500",
        filterRes: "2",
        filterType: false,
        reverbMix: "0.35",
        reverbDecay: "2.0",
        delayTime: "0.25",
        delayFeedback: "0.1",
        tempo: "95",
        attack: "0.02",
        decay: "1.0",
        sustain: "0.45",
        release: "0.6",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth for richness
        oscillatorLevel: "0.85",
        chorusMix: "0.25",
        distortionMix: "0.08",
        flangerMix: "0",
        phaserMix: "0.15",
        lfoRate: "0.05",
        lfoAmount: "60",
        lfoDestination: "release",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2",
        eqMid: "1",
        eqHigh: "-0.5",
        eqMidFreq: "800",
        eqQ: "1.1",
        compressor: "0.3",
        sequencer: [
            {"note": "D3", "active": true},
            {"note": "A3", "active": false},
            {"note": "D4", "active": true},
            {"note": "F#4", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "C#4", "active": false},
            {"note": "E4", "active": true},
            {"note": "A4", "active": false},
            {"note": "F#3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C#4", "active": true},
            {"note": "F#4", "active": false}
        ]
    }),

    // ==== PLUCK PRESETS ====
    createPreset("Crisp Harp", "pluck", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "4000",
        filterRes: "2",
        filterType: false,
        reverbMix: "0.6",
        reverbDecay: "3.0",
        delayTime: "0.3",
        delayFeedback: "0.25",
        tempo: "100",
        attack: "0.001",
        decay: "1.5",
        sustain: "0.1",
        release: "0.8",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.1",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0.25",
        lfoAmount: "25",
        lfoDestination: "delayFeedback",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "0",
        eqMid: "0",
        eqHigh: "3",
        eqMidFreq: "1500",
        eqQ: "1",
        compressor: "0.3",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "D4", "active": true},
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "C5", "active": false},
            {"note": "A4", "active": true},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "D4", "active": true},
            {"note": "C4", "active": true},
            {"note": "C4", "active": false},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "D4", "active": true},
            {"note": "C4", "active": true}
        ]
    }),
    
    createPreset("Techno Plucky", "pluck", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "800",
        filterRes: "8",
        filterType: false,
        reverbMix: "0.2",
        reverbDecay: "1.0",
        delayTime: "0.16",
        delayFeedback: "0.4",
        tempo: "130",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.05",
        release: "0.1",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.9",
        chorusMix: "0",
        distortionMix: "0.1",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "6",
        lfoAmount: "60",
        lfoDestination: "oscillatorLevel",
        lfoWaveform: "square",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "-2",
        eqHigh: "2",
        eqMidFreq: "1000",
        eqQ: "1",
        compressor: "0.3",
        sequencer: [
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true}
        ]
    }),
    
    createPreset("Ethereal Guitar", "pluck", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "2500",
        filterRes: "3",
        filterType: false,
        reverbMix: "0.7",
        reverbDecay: "4.0",
        delayTime: "0.33",
        delayFeedback: "0.5",
        tempo: "90",
        attack: "0.001",
        decay: "0.5",
        sustain: "0.2",
        release: "1.0",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth for richness
        oscillatorLevel: "0.75",
        chorusMix: "0.3",
        distortionMix: "0.05",
        flangerMix: "0.1",
        phaserMix: "0.1",
        lfoRate: "0.15",
        lfoAmount: "35",
        lfoDestination: "chorusMix",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "0",
        eqHigh: "2.5",
        eqMidFreq: "1200",
        eqQ: "1.2",
        compressor: "0.3",
        sequencer: [
            {"note": "E3", "active": true},
            {"note": "B3", "active": false},
            {"note": "E4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "E4", "active": false},
            {"note": "A4", "active": true},
            {"note": "C5", "active": false},
            {"note": "G3", "active": true},
            {"note": "D4", "active": false},
            {"note": "G4", "active": true},
            {"note": "B4", "active": false},
            {"note": "D3", "active": true},
            {"note": "A3", "active": false},
            {"note": "D4", "active": true},
            {"note": "F#4", "active": false}
        ]
    }),

    // ==== BASS PRESETS ====
    createPreset("Deep Sub", "bass", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "300",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.1",
        reverbDecay: "1.0",
        delayTime: "0",
        delayFeedback: "0",
        tempo: "90",
        attack: "0.01",
        decay: "0.2",
        sustain: "0.8",
        release: "0.3",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "1.0",
        chorusMix: "0",
        distortionMix: "0.1",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0.08",
        lfoAmount: "25",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "5",
        eqMid: "-2",
        eqHigh: "-3",
        eqMidFreq: "800",
        eqQ: "1.5",
        compressor: "0.3",
        sequencer: [
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "A#2", "active": true},
            {"note": "A#2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "F2", "active": true},
            {"note": "F2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false}
        ]
    }),
    
    createPreset("Acid Wobble", "bass", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "400",
        filterRes: "12",
        filterType: false,
        reverbMix: "0.1",
        reverbDecay: "1.0",
        delayTime: "0.125", // 1/16th note
        delayFeedback: "0.2",
        tempo: "130",
        attack: "0.01",
        decay: "0.1",
        sustain: "0.6",
        release: "0.2",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "0.9",
        chorusMix: "0",
        distortionMix: "0.4",
        flangerMix: "0",
        phaserMix: "0.1",
        lfoRate: "3.5",
        lfoAmount: "5",
        lfoDestination: "filterCutoff",
        lfoWaveform: "square",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "4",
        eqMid: "0",
        eqHigh: "-2",
        eqMidFreq: "1000",
        eqQ: "1.5",
        compressor: "0.3",
        sequencer: [
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true}
        ]
    }),
    
    createPreset("Synth Funk", "bass", {
        voiceMode: "poly",
        waveform: "square",
        filterCutoff: "800",
        filterRes: "5",
        filterType: false,
        reverbMix: "0.2",
        reverbDecay: "1.5",
        delayTime: "0.15",
        delayFeedback: "0.1",
        tempo: "110",
        attack: "0.01",
        decay: "0.3",
        sustain: "0.4",
        release: "0.2",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.1",
        distortionMix: "0.2",
        flangerMix: "0",
        phaserMix: "0.15",
        lfoRate: "2",
        lfoAmount: "4",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "3",
        eqMid: "1",
        eqHigh: "-1",
        eqMidFreq: "700",
        eqQ: "1.2",
        compressor: "0.3",
        sequencer: [
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "G2", "active": true},
            {"note": "C2", "active": false},
            {"note": "A#2", "active": true},
            {"note": "A#2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "F2", "active": true},
            {"note": "F2", "active": false},
            {"note": "F2", "active": true},
            {"note": "F2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false}
        ]
    }),

    // ==== LEAD PRESETS ====
    createPreset("Screaming Lead", "lead", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "2000",
        filterRes: "6",
        filterType: false,
        reverbMix: "0.3",
        reverbDecay: "1.5",
        delayTime: "0.2",
        delayFeedback: "0.3",
        tempo: "120",
        attack: "0.01",
        decay: "0.3",
        sustain: "0.7",
        release: "0.2",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.19",
        chorusMix: "0.1",
        distortionMix: "0.6",
        flangerMix: "0",
        phaserMix: "0.2",
        lfoRate: "6",
        lfoAmount: "35",
        lfoDestination: "filterRes",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "-1",
        eqMid: "3",
        eqHigh: "4",
        eqMidFreq: "1500",
        eqQ: "1.5",
        compressor: "0.3",
        sequencer: [
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "B4", "active": true},
            {"note": "E5", "active": true},
            {"note": "D5", "active": true},
            {"note": "B4", "active": true},
            {"note": "A4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "B4", "active": true},
            {"note": "D5", "active": true},
            {"note": "E5", "active": true},
            {"note": "G5", "active": true},
            {"note": "E5", "active": true},
            {"note": "B4", "active": true}
        ]
    }),
    
    createPreset("Smooth Solo", "lead", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "1200",
        filterRes: "3",
        filterType: false,
        reverbMix: "0.4",
        reverbDecay: "2.0",
        delayTime: "0.3",
        delayFeedback: "0.4",
        tempo: "90",
        attack: "0.05",
        decay: "0.2",
        sustain: "0.8",
        release: "0.4",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.2",
        distortionMix: "0.1",
        flangerMix: "0",
        phaserMix: "0.3",
        lfoRate: "0.2",
        lfoAmount: "35",
        lfoDestination: "eqMid",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "0",
        eqMid: "2",
        eqHigh: "1",
        eqMidFreq: "1200",
        eqQ: "1.2",
        compressor: "0.3",
        sequencer: [
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "C5", "active": true},
            {"note": "B4", "active": true},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "D4", "active": true},
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "C5", "active": true},
            {"note": "B4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "E4", "active": true}
        ]
    }),
    
    createPreset("Retro Arpeggios", "lead", {
        voiceMode: "poly",
        waveform: "pulse",
        filterCutoff: "1500",
        filterRes: "8",
        filterType: false,
        reverbMix: "0.25",
        reverbDecay: "1.5",
        delayTime: "0.125",
        delayFeedback: "0.6",
        tempo: "140",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.5",
        release: "0.1",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0.1",
        distortionMix: "0.05",
        flangerMix: "0.2",
        phaserMix: "0.1",
        lfoRate: "6",
        lfoAmount: "40",
        lfoDestination: "reverbMix",
        lfoWaveform: "sawtooth",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "0",
        eqMid: "1",
        eqHigh: "3",
        eqMidFreq: "1000",
        eqQ: "1.2",
        compressor: "0.3",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "C5", "active": true},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "A4", "active": true},
            {"note": "E4", "active": true},
            {"note": "C4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true}
        ]
    }),

    // ==== FX PRESETS ====
    createPreset("Alien Transmission", "fx", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "2000",
        filterRes: "15",
        filterType: true, // High pass
        reverbMix: "0.8",
        reverbDecay: "5.0",
        delayTime: "0.4",
        delayFeedback: "0.7",
        tempo: "100",
        attack: "0.05",
        decay: "0.5",
        sustain: "0.3",
        release: "2.0",
        oscillatorOctave: "1",
        oscillatorSemi: "4", // Major third
        oscillatorLevel: "0.7",
        chorusMix: "0.3",
        distortionMix: "0.2",
        flangerMix: "0.3",
        phaserMix: "0.4",
        lfoRate: "3.5",
        lfoAmount: "90",
        lfoDestination: "eqQ",
        lfoWaveform: "square",
        lfoSync: false,
        droneOctave: "0",
        eqLow: "-3",
        eqMid: "0",
        compressor: "0.3",
        eqHigh: "5",
        eqMidFreq: "2000",
        eqQ: "2",
        sequencer: [
            {"note": "C5", "active": true},
            {"note": "C#5", "active": true},
            {"note": "D5", "active": true},
            {"note": "D#5", "active": true},
            {"note": "E5", "active": true},
            {"note": "F5", "active": true},
            {"note": "F#5", "active": true},
            {"note": "G5", "active": true},
            {"note": "G#5", "active": true},
            {"note": "A5", "active": true},
            {"note": "A#5", "active": true},
            {"note": "B5", "active": true},
            {"note": "C6", "active": true},
            {"note": "B5", "active": true},
            {"note": "A#5", "active": true},
            {"note": "A5", "active": true}
        ]
    }),
    
    createPreset("Glitch Machine", "fx", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "1000",
        filterRes: "10",
        filterType: false,
        reverbMix: "0.3",
        reverbDecay: "2.0",
        delayTime: "0.0625", // 1/16th note
        delayFeedback: "0.8",
        tempo: "120",
        attack: "0.001",
        decay: "0.1",
        sustain: "0.1",
        release: "0.1",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0",
        distortionMix: "0.7",
        flangerMix: "0.4",
        phaserMix: "0.3",
        lfoRate: "12",
        lfoAmount: "100",
        lfoDestination: "eqQ",
        lfoWaveform: "random",
        lfoSync: false,
        droneOctave: "0",
        eqLow: "2",
        eqMid: "-4",
        eqHigh: "4",
        eqMidFreq: "1000",
        eqQ: "2.5",
        compressor: "0.3",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "C4", "active": false},
            {"note": "C4", "active": true},
            {"note": "C4", "active": false},
            {"note": "G3", "active": true},
            {"note": "G3", "active": false},
            {"note": "G3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": true},
            {"note": "G3", "active": true},
            {"note": "C4", "active": true},
            {"note": "G3", "active": true},
            {"note": "C4", "active": true},
            {"note": "C4", "active": true},
            {"note": "G3", "active": true},
            {"note": "G3", "active": false}
        ]
    }),
    
    createPreset("Haunted Voices", "fx", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "500",
        filterRes: "4",
        filterType: true, // High pass
        reverbMix: "0.9",
        reverbDecay: "10.0",
        delayTime: "0.5",
        delayFeedback: "0.7",
        tempo: "60",
        attack: "0.5",
        decay: "1.0",
        sustain: "0.4",
        release: "3.0",
        oscillatorOctave: "-1",
        oscillatorSemi: "7", // Perfect fifth
        oscillatorLevel: "0.6",
        chorusMix: "0.4",
        distortionMix: "0.1",
        flangerMix: "0.3",
        phaserMix: "0.2",
        lfoRate: "0.3",
        lfoAmount: "60",
        lfoDestination: "eqLow",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "-2",
        eqMid: "0",
        eqHigh: "3",
        eqMidFreq: "1800",
        eqQ: "1.5",
        compressor: "0.3",
        sequencer: [
            {"note": "G3", "active": true},
            {"note": "C4", "active": false},
            {"note": "G3", "active": false},
            {"note": "A#3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": false},
            {"note": "A#3", "active": false},
            {"note": "G3", "active": true},
            {"note": "F3", "active": false},
            {"note": "G#3", "active": true},
            {"note": "F3", "active": false},
            {"note": "C4", "active": false},
            {"note": "G#3", "active": false},
            {"note": "F3", "active": true},
            {"note": "G3", "active": false},
            {"note": "A#3", "active": false}
        ]
    }),
];

// 10 Professional Synth XR Presets
// Create these high-quality presets that maximize the synth's capabilities

const professionalPresets = [
    // ==== EVOLVING PAD ====
    createPreset("Quantum Field", "pad", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "1200",
        filterRes: "3",
        filterType: false,
        reverbMix: "0.72",
        reverbDecay: "8.4",
        delayTime: "0.375",
        delayFeedback: "0.62",
        tempo: "78",
        attack: "1.8",
        decay: "1.2",
        sustain: "0.75",
        release: "4.2",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth
        oscillatorLevel: "0.82",
        chorusMix: "0.42",
        distortionMix: "0.08",
        flangerMix: "0.21",
        phaserMix: "0.18",
        lfoRate: "0.32",
        lfoAmount: "65",
        lfoDestination: "filterCutoff",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "3.5",
        eqMid: "-1.5",
        eqHigh: "2.5",
        eqMidFreq: "680",
        eqQ: "0.9",
        compressor: "0.25",
        sequencer: [
            {"note": "F3", "active": true},
            {"note": "C4", "active": false},
            {"note": "D#4", "active": true}, // Changed from Eb4
            {"note": "F4", "active": false},
            {"note": "G#3", "active": true}, // Changed from Ab3
            {"note": "C4", "active": false},
            {"note": "D#4", "active": true}, // Changed from Eb4
            {"note": "F4", "active": false},
            {"note": "G3", "active": true},
            {"note": "A#3", "active": false}, // Changed from Bb3
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "D#3", "active": true}, // Changed from Eb3
            {"note": "G3", "active": false},
            {"note": "A#3", "active": true}, // Changed from Bb3
            {"note": "D#4", "active": false} // Changed from Eb4
        ]
    }),
    
    // ==== ANALOG BASS ====
    createPreset("Pressure Bass", "bass", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "520",
        filterRes: "9.2",
        filterType: false,
        reverbMix: "0.15",
        reverbDecay: "1.2",
        delayTime: "0.08",
        delayFeedback: "0.22",
        tempo: "125",
        attack: "0.005",
        decay: "0.32",
        sustain: "0.5",
        release: "0.2",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "0.95",
        chorusMix: "0.08",
        distortionMix: "0.38",
        flangerMix: "0",
        phaserMix: "0.12",
        lfoRate: "2.75",
        lfoAmount: "45",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sawtooth",
        lfoSync: true,
        droneOctave: "-2",
        eqLow: "6",
        eqMid: "1.5",
        eqHigh: "-3",
        eqMidFreq: "520",
        eqQ: "1.8",
        compressor: "0.68",
        sequencer: [
            {"note": "C1", "active": true},
            {"note": "C1", "active": false},
            {"note": "G1", "active": true},
            {"note": "C1", "active": false},
            {"note": "C1", "active": true},
            {"note": "D#1", "active": false}, // Changed from Eb1
            {"note": "G1", "active": true},
            {"note": "D#1", "active": false}, // Changed from Eb1
            {"note": "F1", "active": true},
            {"note": "F1", "active": false},
            {"note": "G1", "active": true},
            {"note": "G1", "active": false},
            {"note": "C1", "active": true},
            {"note": "D#1", "active": false}, // Changed from Eb1
            {"note": "F1", "active": true},
            {"note": "G1", "active": false}
        ]
    }),
    
    // ==== EXPRESSIVE LEAD ====
    createPreset("Solstice Lead", "lead", {
        voiceMode: "poly",
        waveform: "square",
        filterCutoff: "3200",
        filterRes: "5.4",
        filterType: false,
        reverbMix: "0.38",
        reverbDecay: "2.3",
        delayTime: "0.33",
        delayFeedback: "0.48",
        tempo: "118",
        attack: "0.01",
        decay: "0.15",
        sustain: "0.65",
        release: "0.4",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.24",
        distortionMix: "0.28",
        flangerMix: "0",
        phaserMix: "0.15",
        lfoRate: "5.8",
        lfoAmount: "28",
        lfoDestination: "oscillatorLevel",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "3.5",
        eqHigh: "4",
        eqMidFreq: "1800",
        eqQ: "1.4",
        compressor: "0.45",
        sequencer: [
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "B4", "active": true},
            {"note": "D5", "active": true},
            {"note": "G5", "active": true},
            {"note": "D5", "active": true},
            {"note": "B4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "C5", "active": true},
            {"note": "E5", "active": true},
            {"note": "G5", "active": true},
            {"note": "A5", "active": true},
            {"note": "G5", "active": true},
            {"note": "E5", "active": true},
            {"note": "C5", "active": true}
        ]
    }),
    
    // ==== CINEMATIC KEYS ====
    createPreset("Holographic Piano", "keys", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "4200",
        filterRes: "1.8",
        filterType: false,
        reverbMix: "0.65",
        reverbDecay: "3.8",
        delayTime: "0.25",
        delayFeedback: "0.32",
        tempo: "90",
        attack: "0.01",
        decay: "1.5",
        sustain: "0.35",
        release: "1.2",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.88",
        chorusMix: "0.18",
        distortionMix: "0.05",
        flangerMix: "0.1",
        phaserMix: "0.08",
        lfoRate: "0.4",
        lfoAmount: "22",
        lfoDestination: "delayFeedback",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1.5",
        eqMid: "0",
        eqHigh: "4",
        eqMidFreq: "1500",
        eqQ: "1.1",
        compressor: "0.35",
        sequencer: [
            {"note": "D4", "active": true},
            {"note": "A4", "active": false},
            {"note": "F#4", "active": true},
            {"note": "D5", "active": false},
            {"note": "A4", "active": true},
            {"note": "F#4", "active": false},
            {"note": "D4", "active": true},
            {"note": "A3", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "B4", "active": true},
            {"note": "G4", "active": false},
            {"note": "D4", "active": true},
            {"note": "B3", "active": false}
        ]
    }),
    
    // ==== TEXTURED PLUCK ====
    createPreset("Crystalline Pluck", "pluck", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "3400",
        filterRes: "2.5",
        filterType: false,
        reverbMix: "0.68",
        reverbDecay: "3.2",
        delayTime: "0.375", // Dotted eighth note at 120 BPM
        delayFeedback: "0.54",
        tempo: "120",
        attack: "0.001",
        decay: "0.28",
        sustain: "0.12",
        release: "0.9",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth
        oscillatorLevel: "0.82",
        chorusMix: "0.24",
        distortionMix: "0.05",
        flangerMix: "0.15",
        phaserMix: "0",
        lfoRate: "0.35",
        lfoAmount: "42",
        lfoDestination: "eqMidFreq",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "2",
        eqHigh: "3.5",
        eqMidFreq: "1800",
        eqQ: "1.6",
        compressor: "0.3",
        sequencer: [
            {"note": "E4", "active": true},
            {"note": "B4", "active": true},
            {"note": "E5", "active": true},
            {"note": "G5", "active": true},
            {"note": "F#5", "active": true},
            {"note": "E5", "active": true},
            {"note": "B4", "active": true},
            {"note": "A4", "active": false},
            {"note": "G4", "active": true},
            {"note": "D5", "active": true},
            {"note": "G5", "active": true},
            {"note": "B5", "active": true},
            {"note": "A5", "active": true},
            {"note": "G5", "active": true},
            {"note": "D5", "active": true},
            {"note": "B4", "active": false}
        ]
    }),
    
    // ==== EXPERIMENTAL FX ====
    createPreset("Event Horizon", "fx", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "1200",
        filterRes: "12",
        filterType: true, // High pass
        reverbMix: "0.85",
        reverbDecay: "9.5",
        delayTime: "0.667", // Triplet delay
        delayFeedback: "0.78",
        tempo: "90",
        attack: "1.2",
        decay: "2.4",
        sustain: "0.4",
        release: "4.5",
        oscillatorOctave: "1",
        oscillatorSemi: "4", // Major third
        oscillatorLevel: "0.7",
        chorusMix: "0.48",
        distortionMix: "0.25",
        flangerMix: "0.35",
        phaserMix: "0.42",
        lfoRate: "0.15",
        lfoAmount: "85",
        lfoDestination: "filterCutoff",
        lfoWaveform: "random",
        lfoSync: false,
        droneOctave: "0",
        eqLow: "-4",
        eqMid: "0",
        eqHigh: "6",
        eqMidFreq: "2400",
        eqQ: "2.2",
        compressor: "0.4",
        sequencer: [
            {"note": "C5", "active": true},
            {"note": "D#5", "active": false},
            {"note": "G5", "active": true},
            {"note": "A#5", "active": false},
            {"note": "F5", "active": true},
            {"note": "G5", "active": false},
            {"note": "A#5", "active": true},
            {"note": "C6", "active": false},
            {"note": "G4", "active": true},
            {"note": "C5", "active": false},
            {"note": "D#5", "active": true},
            {"note": "G5", "active": false},
            {"note": "F4", "active": true},
            {"note": "A4", "active": false},
            {"note": "C5", "active": true},
            {"note": "F5", "active": false}
        ]
    }),
    
    // ==== 80s RETRO SYNTH ====
    createPreset("1985 Synthwave", "keys", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "1800",
        filterRes: "4.5",
        filterType: false,
        reverbMix: "0.4",
        reverbDecay: "2.8",
        delayTime: "0.167", // 16th note at 90 BPM
        delayFeedback: "0.65",
        tempo: "90",
        attack: "0.001",
        decay: "0.45",
        sustain: "0.6",
        release: "0.38",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.35",
        distortionMix: "0.12",
        flangerMix: "0",
        phaserMix: "0.25",
        lfoRate: "6",
        lfoAmount: "28",
        lfoDestination: "chorusMix",
        lfoWaveform: "triangle",
        lfoSync: true,
        droneOctave: "-1",
        eqLow: "2.5",
        eqMid: "-1",
        eqHigh: "3",
        eqMidFreq: "1100",
        eqQ: "0.8",
        compressor: "0.45",
        sequencer: [
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "A4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "A4", "active": true},
            {"note": "F3", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "F4", "active": true},
            {"note": "G3", "active": true},
            {"note": "B3", "active": true},
            {"note": "D4", "active": true},
            {"note": "G4", "active": true}
        ]
    }),
    
    // ==== MODERN EDM PLUCK ====
    createPreset("Future Pluck", "pluck", {
        voiceMode: "poly",
        waveform: "square",
        filterCutoff: "950",
        filterRes: "8.5",
        filterType: false,
        reverbMix: "0.42",
        reverbDecay: "2.2",
        delayTime: "0.25", // 8th note at 120 BPM
        delayFeedback: "0.56",
        tempo: "128",
        attack: "0.001",
        decay: "0.15",
        sustain: "0.08",
        release: "0.25",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.88",
        chorusMix: "0.15",
        distortionMix: "0.18",
        flangerMix: "0.08",
        phaserMix: "0",
        lfoRate: "4.2",
        lfoAmount: "70",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sawtooth",
        lfoSync: true,
        droneOctave: "-1",
        eqLow: "3",
        eqMid: "-2",
        eqHigh: "4",
        eqMidFreq: "950",
        eqQ: "1.8",
        compressor: "0.6",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "C4", "active": true},
            {"note": "G4", "active": true},
            {"note": "C4", "active": true},
            {"note": "D#4", "active": true}, // Changed from Eb4
            {"note": "C4", "active": true},
            {"note": "G4", "active": true},
            {"note": "D#4", "active": false}, // Changed from Eb4
            {"note": "C4", "active": true},
            {"note": "C4", "active": true},
            {"note": "G4", "active": true},
            {"note": "C4", "active": true},
            {"note": "F4", "active": true},
            {"note": "C4", "active": true},
            {"note": "G4", "active": true},
            {"note": "F4", "active": false}
        ]
    }),
    
    // ==== CINEMATIC ATMOSPHERIC ====
    createPreset("Interstellar", "pad", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "680",
        filterRes: "2.8",
        filterType: false,
        reverbMix: "0.92",
        reverbDecay: "9.8",
        delayTime: "0.5",
        delayFeedback: "0.72",
        tempo: "70",
        attack: "2.5",
        decay: "3.0",
        sustain: "0.85",
        release: "6.0",
        oscillatorOctave: "0",
        oscillatorSemi: "5", // Perfect fourth
        oscillatorLevel: "0.8",
        chorusMix: "0.48",
        distortionMix: "0.05",
        flangerMix: "0.22",
        phaserMix: "0.15",
        lfoRate: "0.08",
        lfoAmount: "48",
        lfoDestination: "eqMidFreq",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "3.5",
        eqMid: "-1",
        eqHigh: "2.5",
        eqMidFreq: "620",
        eqQ: "0.7",
        compressor: "0.3",
        sequencer: [
            {"note": "D3", "active": true},
            {"note": "A3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "D4", "active": false},
            {"note": "F#4", "active": true},
            {"note": "A4", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "E4", "active": false},
            {"note": "A4", "active": true},
            {"note": "C#5", "active": false}
        ]
    }),
    
    // ==== TECHNO SEQUENCE ====
    createPreset("Berlin Techno", "bass", {
        voiceMode: "poly",
        waveform: "pulse",
        filterCutoff: "600",
        filterRes: "9.8",
        filterType: false,
        reverbMix: "0.15",
        reverbDecay: "1.5",
        delayTime: "0.125", // 16th note at 120 BPM
        delayFeedback: "0.35",
        tempo: "126",
        attack: "0.001",
        decay: "0.18",
        sustain: "0.3",
        release: "0.15",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "0.92",
        chorusMix: "0",
        distortionMix: "0.25",
        flangerMix: "0",
        phaserMix: "0.1",
        lfoRate: "8",
        lfoAmount: "55",
        lfoDestination: "filterCutoff",
        lfoWaveform: "square",
        lfoSync: true,
        droneOctave: "-2",
        eqLow: "5",
        eqMid: "-1",
        eqHigh: "-2",
        eqMidFreq: "780",
        eqQ: "1.8",
        compressor: "0.68",
        sequencer: [
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "D#2", "active": true}, // Changed from Eb2
            {"note": "D#2", "active": false}, // Changed from Eb2
            {"note": "D#2", "active": true}, // Changed from Eb2
            {"note": "D#2", "active": false}, // Changed from Eb2
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "G2", "active": true},
            {"note": "F2", "active": true}
        ]
    }),
    
    // ==== HYBRID ORCHESTRAL LEAD ====
    createPreset("Hybrid Orchestra", "lead", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "3800",
        filterRes: "1.2",
        filterType: false,
        reverbMix: "0.78",
        reverbDecay: "4.6",
        delayTime: "0.375", // Dotted eighth note
        delayFeedback: "0.42",
        tempo: "100",
        attack: "0.05",
        decay: "0.8",
        sustain: "0.7",
        release: "1.5",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.86",
        chorusMix: "0.28",
        distortionMix: "0.1",
        flangerMix: "0.15",
        phaserMix: "0",
        lfoRate: "0.3",
        lfoAmount: "32",
        lfoDestination: "chorusMix",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2",
        eqMid: "1.5",
        eqHigh: "3",
        eqMidFreq: "1500",
        eqQ: "1.2",
        compressor: "0.4",
        sequencer: [
            {"note": "G3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "C5", "active": true},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "C4", "active": false},
            {"note": "F3", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "F4", "active": true},
            {"note": "A4", "active": true},
            {"note": "F4", "active": true},
            {"note": "C4", "active": true},
            {"note": "A3", "active": false}
        ]
    }),
    
    // ==== PSYCHEDELIC DRONE ====
    createPreset("Psychedelic Voyage", "fx", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "900",
        filterRes: "6.5",
        filterType: true, // High pass
        reverbMix: "0.82",
        reverbDecay: "8.5",
        delayTime: "0.667", // Triplet
        delayFeedback: "0.75",
        tempo: "85",
        attack: "1.0",
        decay: "2.5",
        sustain: "0.6",
        release: "5.0",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth
        oscillatorLevel: "0.75",
        chorusMix: "0.65",
        distortionMix: "0.15",
        flangerMix: "0.45",
        phaserMix: "0.55",
        lfoRate: "0.15",
        lfoAmount: "75",
        lfoDestination: "phaserMix",
        lfoWaveform: "random",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "3",
        eqHigh: "2",
        eqMidFreq: "1200",
        eqQ: "2.4",
        compressor: "0.35",
        sequencer: [
            {"note": "C3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": true},
            {"note": "D#4", "active": false}, // Changed from Eb4
            {"note": "G4", "active": true},
            {"note": "A#4", "active": false}, // Changed from Bb4
            {"note": "C5", "active": true},
            {"note": "G4", "active": false},
            {"note": "D#4", "active": true}, // Changed from Eb4
            {"note": "C4", "active": false},
            {"note": "G3", "active": true},
            {"note": "C3", "active": false},
            {"note": "D#3", "active": true}, // Changed from Eb3
            {"note": "G3", "active": false},
            {"note": "A#3", "active": true}, // Changed from Bb3
            {"note": "C4", "active": false}
        ]
    })
];

// Add these presets to the built-in presets array
builtInPresets.push(...professionalPresets);

// Export the presets for use in other modules
export { builtInPresets, createPreset };