// Synth XR Presets

const createPreset = (name, category, settings) => ({
    name,
    category,
    settings
});

const generateDrumLoop = (kickSteps, snareSteps, hihatSteps, clapSteps, kickVol = 0.8, snareVol = 0.7, hihatVol = 0.6, clapVol = 0.65) => ({
    kick: { volume: kickVol, steps: kickSteps },
    snare: { volume: snareVol, steps: snareSteps },
    hihat: { volume: hihatVol, steps: hihatSteps },
    clap: { volume: clapVol, steps: clapSteps }
});

const builtInPresets = [
    createPreset("Default", "pad", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "900",
        filterRes: "5",
        filterType: false,
        reverbMix: "0.6",
        reverbDecay: "3.5",
        delayTime: "0.33",
        delayFeedback: "0.55",
        tempo: "96",
        attack: "0.02",
        decay: "0.18",
        sustain: "0.35",
        release: "1.4",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0.1",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "1",
        lfoAmount: "50",
        lfoDestination: "off",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2",
        eqMid: "0",
        eqHigh: "1",
        eqMidFreq: "1000",
        eqQ: "1",
        sequencer: [
            {"note": "E3", "active": true},
            {"note": "B3", "active": true},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "B3", "active": true},
            {"note": "C4", "active": false},
            {"note": "G3", "active": true},
            {"note": "D4", "active": true},
            {"note": "B3", "active": true},
            {"note": "D4", "active": false},
            {"note": "F#3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E3", "active": true},
            {"note": "B3", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false]
        )
    }),

    // ==== PAD PRESETS ====
    createPreset("Ethereal Waves", "pad", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "1200",
        filterRes: "2",
        filterType: false,
        reverbMix: "0.85",
        reverbDecay: "8.0",
        delayTime: "0.5",
        delayFeedback: "0.4",
        tempo: "80",
        attack: "1.5",
        decay: "2.0",
        sustain: "0.7",
        release: "4.0",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth
        oscillatorLevel: "0.7",
        chorusMix: "0.3",
        distortionMix: "0",
        flangerMix: "0.15",
        phaserMix: "0.1",
        lfoRate: "0.2",
        lfoAmount: "40",
        lfoDestination: "filterCutoff",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "3",
        eqMid: "-1",
        eqHigh: "2",
        eqMidFreq: "800",
        eqQ: "0.8",
        sequencer: [
            {"note": "A3", "active": true},
            {"note": "C4", "active": false},
            {"note": "E4", "active": true},
            {"note": "A4", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "F3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C4", "active": true},
            {"note": "F4", "active": false},
            {"note": "E3", "active": true},
            {"note": "G3", "active": false},
            {"note": "B3", "active": true},
            {"note": "E4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false],
            [false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
            0.6, 0.5, 0.4, 0.5
        )
    }),
    
    createPreset("Cosmic Atmosphere", "pad", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "800",
        filterRes: "4",
        filterType: false,
        reverbMix: "0.9",
        reverbDecay: "7.5",
        delayTime: "0.75",
        delayFeedback: "0.6",
        tempo: "72",
        attack: "2.0",
        decay: "1.5",
        sustain: "0.8",
        release: "5.0",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.75",
        chorusMix: "0.4",
        distortionMix: "0.05",
        flangerMix: "0.2",
        phaserMix: "0.15",
        lfoRate: "0.15",
        lfoAmount: "70",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "4",
        eqMid: "-2",
        eqHigh: "3",
        eqMidFreq: "700",
        eqQ: "0.7",
        sequencer: [
            {"note": "C3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "C5", "active": false},
            {"note": "G4", "active": true},
            {"note": "E4", "active": false},
            {"note": "C4", "active": true},
            {"note": "G3", "active": false},
            {"note": "E3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "C5", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            [false, false, true, false, false, true, false, true, false, false, true, false, false, true, false, true],
            [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true],
            0.5, 0.4, 0.35, 0.5
        )
    }),
    
    createPreset("Floating Dreams", "pad", {
        voiceMode: "poly",
        waveform: "fatsawtooth",
        filterCutoff: "600",
        filterRes: "6",
        filterType: false,
        reverbMix: "0.8",
        reverbDecay: "6.0",
        delayTime: "0.4",
        delayFeedback: "0.5",
        tempo: "88",
        attack: "1.2",
        decay: "1.8",
        sustain: "0.6",
        release: "3.5",
        oscillatorOctave: "0",
        oscillatorSemi: "4", // Major third
        oscillatorLevel: "0.65",
        chorusMix: "0.35",
        distortionMix: "0.02",
        flangerMix: "0.1",
        phaserMix: "0.2",
        lfoRate: "0.25",
        lfoAmount: "45",
        lfoDestination: "reverbMix",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2.5",
        eqMid: "0",
        eqHigh: "1.5",
        eqMidFreq: "900",
        eqQ: "0.9",
        sequencer: [
            {"note": "F3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C4", "active": true},
            {"note": "F4", "active": false},
            {"note": "Eb3", "active": true},
            {"note": "G3", "active": false},
            {"note": "Bb3", "active": true},
            {"note": "Eb4", "active": false},
            {"note": "Bb2", "active": true},
            {"note": "D3", "active": false},
            {"note": "F3", "active": true},
            {"note": "Bb3", "active": false},
            {"note": "C3", "active": true},
            {"note": "E3", "active": false},
            {"note": "G3", "active": true},
            {"note": "C4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, false, false, true, false, true, false, false, false, false, false, true, false],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false],
            0.6, 0.45, 0.4, 0.5
        )
    }),

    // ==== KEYS PRESETS ====
    createPreset("Crystal Piano", "keys", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "3500",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.45",
        reverbDecay: "2.5",
        delayTime: "0.2",
        delayFeedback: "0.15",
        tempo: "110",
        attack: "0.01",
        decay: "1.2",
        sustain: "0.4",
        release: "0.8",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.9",
        chorusMix: "0.1",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "5",
        lfoAmount: "15",
        lfoDestination: "oscillatorLevel",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "0.5",
        eqHigh: "2.5",
        eqMidFreq: "1200",
        eqQ: "1.2",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "C5", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "C4", "active": false},
            {"note": "E4", "active": true},
            {"note": "A4", "active": false},
            {"note": "F3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C4", "active": true},
            {"note": "F4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false]
        )
    }),
    
    createPreset("Vintage Electric", "keys", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "2000",
        filterRes: "3",
        filterType: false,
        reverbMix: "0.3",
        reverbDecay: "1.5",
        delayTime: "0.15",
        delayFeedback: "0.2",
        tempo: "120",
        attack: "0.005",
        decay: "0.8",
        sustain: "0.5",
        release: "0.4",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.2",
        distortionMix: "0.15",
        flangerMix: "0",
        phaserMix: "0.2",
        lfoRate: "4",
        lfoAmount: "20",
        lfoDestination: "oscillatorLevel",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1.5",
        eqMid: "-1",
        eqHigh: "3",
        eqMidFreq: "1000",
        eqQ: "1",
        sequencer: [
            {"note": "E3", "active": true},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "E3", "active": true},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": false},
            {"note": "G4", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false]
        )
    }),
    
    createPreset("Warm Rhodes", "keys", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "1500",
        filterRes: "2",
        filterType: false,
        reverbMix: "0.35",
        reverbDecay: "2.0",
        delayTime: "0.25",
        delayFeedback: "0.1",
        tempo: "95",
        attack: "0.02",
        decay: "1.0",
        sustain: "0.45",
        release: "0.6",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth for richness
        oscillatorLevel: "0.8",
        chorusMix: "0.15",
        distortionMix: "0.05",
        flangerMix: "0",
        phaserMix: "0.1",
        lfoRate: "0.8",
        lfoAmount: "15",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2",
        eqMid: "1",
        eqHigh: "-0.5",
        eqMidFreq: "800",
        eqQ: "1.1",
        sequencer: [
            {"note": "D3", "active": true},
            {"note": "A3", "active": false},
            {"note": "D4", "active": true},
            {"note": "F#4", "active": false},
            {"note": "G3", "active": true},
            {"note": "B3", "active": false},
            {"note": "D4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "C#4", "active": false},
            {"note": "E4", "active": true},
            {"note": "A4", "active": false},
            {"note": "F#3", "active": true},
            {"note": "A3", "active": false},
            {"note": "C#4", "active": true},
            {"note": "F#4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, true, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false]
        )
    }),

    // ==== PLUCK PRESETS ====
    createPreset("Crisp Harp", "pluck", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "4000",
        filterRes: "2",
        filterType: false,
        reverbMix: "0.6",
        reverbDecay: "3.0",
        delayTime: "0.3",
        delayFeedback: "0.25",
        tempo: "100",
        attack: "0.001",
        decay: "1.5",
        sustain: "0.1",
        release: "0.8",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.1",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0.4",
        lfoAmount: "18",
        lfoDestination: "delayFeedback",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "0",
        eqMid: "0",
        eqHigh: "3",
        eqMidFreq: "1500",
        eqQ: "1",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "D4", "active": true},
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "C5", "active": false},
            {"note": "A4", "active": true},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "D4", "active": true},
            {"note": "C4", "active": true},
            {"note": "C4", "active": false},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "D4", "active": true},
            {"note": "C4", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false]
        )
    }),
    
    createPreset("Techno Plucky", "pluck", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "800",
        filterRes: "8",
        filterType: false,
        reverbMix: "0.2",
        reverbDecay: "1.0",
        delayTime: "0.16",
        delayFeedback: "0.4",
        tempo: "130",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.05",
        release: "0.1",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.9",
        chorusMix: "0",
        distortionMix: "0.1",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "8",
        lfoAmount: "30",
        lfoDestination: "filterCutoff",
        lfoWaveform: "square",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "-2",
        eqHigh: "2",
        eqMidFreq: "1000",
        eqQ: "1",
        sequencer: [
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "A3", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            0.9, 0.8, 0.7, 0.75
        )
    }),
    
    createPreset("Ethereal Guitar", "pluck", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "2500",
        filterRes: "3",
        filterType: false,
        reverbMix: "0.7",
        reverbDecay: "4.0",
        delayTime: "0.33",
        delayFeedback: "0.5",
        tempo: "90",
        attack: "0.001",
        decay: "0.5",
        sustain: "0.2",
        release: "1.0",
        oscillatorOctave: "0",
        oscillatorSemi: "7", // Perfect fifth for richness
        oscillatorLevel: "0.75",
        chorusMix: "0.3",
        distortionMix: "0.05",
        flangerMix: "0.1",
        phaserMix: "0.1",
        lfoRate: "0.3",
        lfoAmount: "25",
        lfoDestination: "chorusMix",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "1",
        eqMid: "0",
        eqHigh: "2.5",
        eqMidFreq: "1200",
        eqQ: "1.2",
        sequencer: [
            {"note": "E3", "active": true},
            {"note": "B3", "active": false},
            {"note": "E4", "active": true},
            {"note": "G4", "active": false},
            {"note": "A3", "active": true},
            {"note": "E4", "active": false},
            {"note": "A4", "active": true},
            {"note": "C5", "active": false},
            {"note": "G3", "active": true},
            {"note": "D4", "active": false},
            {"note": "G4", "active": true},
            {"note": "B4", "active": false},
            {"note": "D3", "active": true},
            {"note": "A3", "active": false},
            {"note": "D4", "active": true},
            {"note": "F#4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false],
            [false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false],
            [false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false],
            0.6, 0.5, 0.4, 0.5
        )
    }),

    // ==== BASS PRESETS ====
    createPreset("Deep Sub", "bass", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "300",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.1",
        reverbDecay: "1.0",
        delayTime: "0",
        delayFeedback: "0",
        tempo: "90",
        attack: "0.01",
        decay: "0.2",
        sustain: "0.8",
        release: "0.3",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "1.0",
        chorusMix: "0",
        distortionMix: "0.1",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0.25",
        lfoAmount: "20",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "5",
        eqMid: "-2",
        eqHigh: "-3",
        eqMidFreq: "500",
        eqQ: "0.8",
        sequencer: [
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "A#2", "active": true},
            {"note": "A#2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "F2", "active": true},
            {"note": "F2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            0.9, 0.7, 0.5, 0.6
        )
    }),
    
    createPreset("Acid Wobble", "bass", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "400",
        filterRes: "12",
        filterType: false,
        reverbMix: "0.1",
        reverbDecay: "1.0",
        delayTime: "0.125",
        delayFeedback: "0.2",
        tempo: "130",
        attack: "0.01",
        decay: "0.1",
        sustain: "0.6",
        release: "0.2",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "0.9",
        chorusMix: "0",
        distortionMix: "0.4",
        flangerMix: "0",
        phaserMix: "0.1",
        lfoRate: "4",
        lfoAmount: "80",
        lfoDestination: "filterCutoff",
        lfoWaveform: "square",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "4",
        eqMid: "0",
        eqHigh: "-2",
        eqMidFreq: "800",
        eqQ: "1.5",
        sequencer: [
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "C2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true},
            {"note": "G2", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, true, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true],
            0.9, 0.7, 0.6, 0.7
        )
    }),
    
    createPreset("Synth Funk", "bass", {
        voiceMode: "poly",
        waveform: "square",
        filterCutoff: "800",
        filterRes: "5",
        filterType: false,
        reverbMix: "0.2",
        reverbDecay: "1.5",
        delayTime: "0.15",
        delayFeedback: "0.1",
        tempo: "110",
        attack: "0.01",
        decay: "0.3",
        sustain: "0.4",
        release: "0.2",
        oscillatorOctave: "-1",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.1",
        distortionMix: "0.2",
        flangerMix: "0",
        phaserMix: "0.15",
        lfoRate: "2",
        lfoAmount: "40",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-2",
        eqLow: "3",
        eqMid: "1",
        eqHigh: "-1",
        eqMidFreq: "700",
        eqQ: "1.2",
        sequencer: [
            {"note": "C2", "active": true},
            {"note": "C2", "active": false},
            {"note": "G2", "active": true},
            {"note": "C2", "active": false},
            {"note": "A#2", "active": true},
            {"note": "A#2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "F2", "active": true},
            {"note": "F2", "active": false},
            {"note": "F2", "active": true},
            {"note": "F2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false},
            {"note": "G2", "active": true},
            {"note": "G2", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, true, false, false, true, false, true, false, false, true, false, false, true, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            0.85, 0.7, 0.65, 0.7
        )
    }),

    // ==== LEAD PRESETS ====
    createPreset("Screaming Lead", "lead", {
        voiceMode: "poly",
        waveform: "fatsawtooth",
        filterCutoff: "2000",
        filterRes: "6",
        filterType: false,
        reverbMix: "0.3",
        reverbDecay: "1.5",
        delayTime: "0.2",
        delayFeedback: "0.3",
        tempo: "120",
        attack: "0.01",
        decay: "0.3",
        sustain: "0.7",
        release: "0.2",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.9",
        chorusMix: "0.1",
        distortionMix: "0.6",
        flangerMix: "0",
        phaserMix: "0.2",
        lfoRate: "6",
        lfoAmount: "35",
        lfoDestination: "filterRes",
        lfoWaveform: "triangle",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "-1",
        eqMid: "3",
        eqHigh: "4",
        eqMidFreq: "1500",
        eqQ: "1.5",
        sequencer: [
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "B4", "active": true},
            {"note": "E5", "active": true},
            {"note": "D5", "active": true},
            {"note": "B4", "active": true},
            {"note": "A4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "B4", "active": true},
            {"note": "D5", "active": true},
            {"note": "E5", "active": true},
            {"note": "G5", "active": true},
            {"note": "E5", "active": true},
            {"note": "B4", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            0.8, 0.7, 0.6, 0.7
        )
    }),
    
    createPreset("Smooth Solo", "lead", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "1200",
        filterRes: "3",
        filterType: false,
        reverbMix: "0.4",
        reverbDecay: "2.0",
        delayTime: "0.3",
        delayFeedback: "0.4",
        tempo: "90",
        attack: "0.05",
        decay: "0.2",
        sustain: "0.8",
        release: "0.4",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.85",
        chorusMix: "0.2",
        distortionMix: "0.1",
        flangerMix: "0",
        phaserMix: "0.3",
        lfoRate: "5",
        lfoAmount: "20",
        lfoDestination: "oscillatorLevel",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "0",
        eqMid: "2",
        eqHigh: "1",
        eqMidFreq: "1200",
        eqQ: "1.2",
        sequencer: [
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "C5", "active": true},
            {"note": "B4", "active": true},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "D4", "active": true},
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "C5", "active": true},
            {"note": "B4", "active": true},
            {"note": "G4", "active": true},
            {"note": "A4", "active": true},
            {"note": "E4", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            0.7, 0.6, 0.5, 0.6
        )
    }),
    
    createPreset("Retro Arpeggios", "lead", {
        voiceMode: "poly",
        waveform: "pulse",
        filterCutoff: "1500",
        filterRes: "8",
        filterType: false,
        reverbMix: "0.25",
        reverbDecay: "1.5",
        delayTime: "0.125",
        delayFeedback: "0.6",
        tempo: "140",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.5",
        release: "0.1",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0.1",
        distortionMix: "0.05",
        flangerMix: "0.2",
        phaserMix: "0.1",
        lfoRate: "8",
        lfoAmount: "30",
        lfoDestination: "filterCutoff",
        lfoWaveform: "sawtooth",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "0",
        eqMid: "1",
        eqHigh: "3",
        eqMidFreq: "1000",
        eqQ: "1.2",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "G4", "active": true},
            {"note": "C5", "active": true},
            {"note": "G4", "active": true},
            {"note": "E4", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true},
            {"note": "E4", "active": true},
            {"note": "A4", "active": true},
            {"note": "E4", "active": true},
            {"note": "C4", "active": true},
            {"note": "A3", "active": true},
            {"note": "C4", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
            0.8, 0.7, 0.6, 0.7
        )
    }),

    // ==== FX PRESETS ====
    createPreset("Alien Transmission", "fx", {
        voiceMode: "poly",
        waveform: "fmsine",
        filterCutoff: "2000",
        filterRes: "15",
        filterType: true, // High pass
        reverbMix: "0.8",
        reverbDecay: "5.0",
        delayTime: "0.4",
        delayFeedback: "0.7",
        tempo: "100",
        attack: "0.05",
        decay: "0.5",
        sustain: "0.3",
        release: "2.0",
        oscillatorOctave: "1",
        oscillatorSemi: "4", // Major third
        oscillatorLevel: "0.7",
        chorusMix: "0.3",
        distortionMix: "0.2",
        flangerMix: "0.3",
        phaserMix: "0.4",
        lfoRate: "3",
        lfoAmount: "90",
        lfoDestination: "filterCutoff",
        lfoWaveform: "square",
        lfoSync: false,
        droneOctave: "0",
        eqLow: "-3",
        eqMid: "0",
        eqHigh: "5",
        eqMidFreq: "2000",
        eqQ: "2",
        sequencer: [
            {"note": "C5", "active": true},
            {"note": "C#5", "active": true},
            {"note": "D5", "active": true},
            {"note": "D#5", "active": true},
            {"note": "E5", "active": true},
            {"note": "F5", "active": true},
            {"note": "F#5", "active": true},
            {"note": "G5", "active": true},
            {"note": "G#5", "active": true},
            {"note": "A5", "active": true},
            {"note": "A#5", "active": true},
            {"note": "B5", "active": true},
            {"note": "C6", "active": true},
            {"note": "B5", "active": true},
            {"note": "A#5", "active": true},
            {"note": "A5", "active": true}
        ],
        drumMachine: generateDrumLoop(
            [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
            [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
            [false, true, false, true, false, false, true, false, true, false, false, true, false, true, false, true],
            [true, false, true, false, true, false, false, true, false, true, false, false, true, false, true, false],
            0.5, 0.4, 0.7, 0.6
        )
    }),
    
    createPreset("Glitch Machine", "fx", {
        voiceMode: "poly",
        waveform: "sawtooth",
        filterCutoff: "1000",
        filterRes: "10",
        filterType: false,
        reverbMix: "0.3",
        reverbDecay: "2.0",
        delayTime: "0.0625", // 1/16th note
        delayFeedback: "0.8",
        tempo: "120",
        attack: "0.001",
        decay: "0.1",
        sustain: "0.1",
        release: "0.1",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0",
        distortionMix: "0.7",
        flangerMix: "0.4",
        phaserMix: "0.3",
        lfoRate: "16",
        lfoAmount: "100",
        lfoDestination: "filterRes",
        lfoWaveform: "square",
        lfoSync: false,
        droneOctave: "0",
        eqLow: "2",
        eqMid: "-4",
        eqHigh: "4",
        eqMidFreq: "1000",
        eqQ: "2.5",
        sequencer: [
            {"note": "C4", "active": true},
            {"note": "C4", "active": false},
            {"note": "C4", "active": true},
            {"note": "C4", "active": false},
            {"note": "G3", "active": true},
            {"note": "G3", "active": false},
            {"note": "G3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": true},
            {"note": "G3", "active": true},
            {"note": "C4", "active": true},
            {"note": "G3", "active": true},
            {"note": "C4", "active": true},
            {"note": "C4", "active": false},
            {"note": "G3", "active": true},
            {"note": "G3", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false],
            [false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true],
            [true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true],
            [false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false],
            0.7, 0.7, 0.7, 0.7
        )
    }),
    
    createPreset("Haunted Voices", "fx", {
        voiceMode: "poly",
        waveform: "sine",
        filterCutoff: "500",
        filterRes: "4",
        filterType: true, // High pass
        reverbMix: "0.9",
        reverbDecay: "10.0",
        delayTime: "0.5",
        delayFeedback: "0.7",
        tempo: "60",
        attack: "0.5",
        decay: "1.0",
        sustain: "0.4",
        release: "3.0",
        oscillatorOctave: "-1",
        oscillatorSemi: "7", // Perfect fifth
        oscillatorLevel: "0.6",
        chorusMix: "0.4",
        distortionMix: "0.1",
        flangerMix: "0.3",
        phaserMix: "0.2",
        lfoRate: "0.1",
        lfoAmount: "60",
        lfoDestination: "phaserMix",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "-2",
        eqMid: "0",
        eqHigh: "3",
        eqMidFreq: "1800",
        eqQ: "1.5",
        sequencer: [
            {"note": "G3", "active": true},
            {"note": "C4", "active": false},
            {"note": "G3", "active": false},
            {"note": "Bb3", "active": true},
            {"note": "G3", "active": false},
            {"note": "C4", "active": false},
            {"note": "Bb3", "active": false},
            {"note": "G3", "active": true},
            {"note": "F3", "active": false},
            {"note": "Ab3", "active": true},
            {"note": "F3", "active": false},
            {"note": "C4", "active": false},
            {"note": "Ab3", "active": false},
            {"note": "F3", "active": true},
            {"note": "G3", "active": false},
            {"note": "Bb3", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
            [false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false],
            [false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
            [false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false],
            0.4, 0.3, 0.3, 0.4
        )
    }),

    // ==== SPECIAL DRUM PRESETS ====
    createPreset("Drum Loop 1", "drums", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "5000",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.2",
        reverbDecay: "1.0",
        delayTime: "0",
        delayFeedback: "0",
        tempo: "120",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.1",
        release: "0.3",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0",
        lfoAmount: "0",
        lfoDestination: "off",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "2",
        eqMid: "0",
        eqHigh: "1.5",
        eqMidFreq: "1000",
        eqQ: "1",
        sequencer: [
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, true],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
            [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
            [false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false],
            0.85, 0.75, 0.7, 0.75
        )
    }),
    
    createPreset("Drum Loop 2", "drums", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "5000",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.3",
        reverbDecay: "1.2",
        delayTime: "0",
        delayFeedback: "0",
        tempo: "95",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.1",
        release: "0.3",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0",
        lfoAmount: "0",
        lfoDestination: "off",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "3",
        eqMid: "-1",
        eqHigh: "2",
        eqMidFreq: "1000",
        eqQ: "1",
        sequencer: [
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, true, false, false, true, false, true, false, false, true, false, false, true],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true],
            [false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true],
            [false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
            0.9, 0.7, 0.6, 0.7
        )
    }),
    
    createPreset("Drum Loop 3", "drums", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "5000",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.4",
        reverbDecay: "1.5",
        delayTime: "0",
        delayFeedback: "0",
        tempo: "135",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.1",
        release: "0.3",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0",
        lfoAmount: "0",
        lfoDestination: "off",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "4",
        eqMid: "0",
        eqHigh: "2",
        eqMidFreq: "1000",
        eqQ: "1",
        sequencer: [
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
            [false, false, true, false, false, false, true, false, false, false, true, false, false, true, false, true],
            [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
            [false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false],
            0.9, 0.75, 0.65, 0.8
        )
    }),
    
    createPreset("Drum Loop 4", "drums", {
        voiceMode: "poly",
        waveform: "triangle",
        filterCutoff: "5000",
        filterRes: "1",
        filterType: false,
        reverbMix: "0.5",
        reverbDecay: "2.0",
        delayTime: "0",
        delayFeedback: "0",
        tempo: "80",
        attack: "0.001",
        decay: "0.2",
        sustain: "0.1",
        release: "0.3",
        oscillatorOctave: "0",
        oscillatorSemi: "0",
        oscillatorLevel: "0.8",
        chorusMix: "0",
        distortionMix: "0",
        flangerMix: "0",
        phaserMix: "0",
        lfoRate: "0",
        lfoAmount: "0",
        lfoDestination: "off",
        lfoWaveform: "sine",
        lfoSync: false,
        droneOctave: "-1",
        eqLow: "3.5",
        eqMid: "-1",
        eqHigh: "1.5",
        eqMidFreq: "1000",
        eqQ: "1",
        sequencer: [
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false},
            {"note": "C4", "active": false}
        ],
        drumMachine: generateDrumLoop(
            [true, false, false, false, false, false, false, false, true, false, false, true, false, false, true, false],
            [false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true],
            [false, false, true, false, false, true, false, true, false, true, false, true, false, true, false, true],
            [true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false],
            0.85, 0.7, 0.5, 0.7
        )
    })
];

// Export the presets for use in other modules
export { builtInPresets, createPreset, generateDrumLoop };